{% set name = "cloudevents" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloudevents-{{ version }}.tar.gz
  sha256: 5be990583e99f3b08af5a709460e20b25cb169270227957a20b47a6ec8635e66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - deprecation >=2.0,<3.0
    - pydantic >=1.0.0,<3.0

test:
  imports:
    - cloudevents
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/cloudevents/sdk-python
  summary: CloudEvents Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
