{% set name = "cloudevents" %}
{% set version = "1.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloudevents-{{ version }}.tar.gz
  sha256: 1eb52051309c3228934f86f41d50bd02c0e3d9561e5876e73ad8ad9f98f0d3ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - deprecation >=2.0,<3.0
    - pydantic >=1.0.0,<3.0

test:
  imports:
    - cloudevents
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/cloudevents/sdk-python
  summary: CloudEvents Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
